# .github/workflows/backend.yml

name: CI/CD - Backend

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository's code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Logs in to Docker Hub using your secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Builds your Docker image and pushes it to Docker Hub
      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: amarnarayandwivedi/apexquest-backend:latest

      # Step 4: Calls the Render deploy hook to trigger the new deployment
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
