# .github/workflows/frontend.yml

# A friendly name for the frontend pipeline
name: CI/CD - Frontend

# This pipeline is also triggered by a push to the 'main' branch
on:
  push:
    branches: ["main"]

jobs:
  build-push-and-deploy:
    # Runs on the same type of virtual machine
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub (Required to push the image)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push the frontend image to Docker Hub
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend # Point to the 'frontend' folder
          push: true
          tags: amarnarayandwivedi/apexquest-frontend:latest # Use the frontend image name
          build-args: |
            VITE_FIREBASE_APIKEY=${{ secrets.VITE_FIREBASE_APIKEY }}
            VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL_PROD }}

      # Step 4: Trigger the frontend deployment on Render
      - name: Trigger Render Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
